export const mockJobs = [
  {
    id: "ai-research-scientist",
    title: "AI Research Scientist",
    team: "Technology",
    location: "Remote (India)",
    type: "Full-time",
    experience: "Mid-level (2–5 years)",
    postedText: "Posted 2 days ago",
    postedDays: 2,
    tags: ["Python", "Machine Learning", "Research", "Data Analysis"],
    description:
      "Work on cutting-edge AI research to solve real-world problems for global impact. You’ll collaborate with a multidisciplinary team to build innovative solutions.",
    responsibilities: [
      "Conduct research and develop novel AI/ML solutions",
      "Analyze complex datasets and derive meaningful insights",
      "Collaborate with cross-functional teams to integrate AI models into production",
      "Publish research findings and contribute to open-source initiatives",
      "Stay up to date with the latest advancements in AI and machine learning",
    ],
    skills: [
      "2–5 years of relevant AI/ML research or engineering experience",
      "Strong programming skills in Python and deep learning frameworks",
      "Experience in machine learning, statistical modeling, and data analysis",
      "Research mindset and structured problem-solving approach",
      "Excellent communication and cross-functional collaboration skills",
    ],
    requirements: [
      "Bachelor's or Master's degree in Computer Science, AI, or equivalent field",
      "Demonstrated experience training and evaluating ML models",
      "Ability to work autonomously in a distributed remote team",
    ],
  },
  {
    id: "product-manager",
    title: "Product Manager",
    team: "Product Management",
    location: "Remote",
    type: "Full-time",
    experience: "Mid-level (2–5 years)",
    postedText: "Posted 5 days ago",
    postedDays: 5,
    tags: ["Product Strategy", "User Research", "Roadmapping", "Analytics"],
    description:
      "Manage features and drive product success across the GharPadharo platform. You'll bridge customer needs with engineering execution to deliver exceptional user journeys.",
    responsibilities: [
      "Define product requirements, user stories, and acceptance criteria",
      "Collaborate closely with design, engineering, and operations teams",
      "Conduct user research and analyze data metrics to guide product decisions",
      "Oversee feature lifecycles from ideation to launch and post-launch iteration",
      "Communicate roadmap priorities and strategic alignment to stakeholders",
    ],
    skills: [
      "2–5 years of product management experience in tech platforms",
      "Demonstrated ability to drive product roadmaps and sprint planning",
      "Data-driven mindset with proficiency in user analytics and experimentation",
      "Strong customer empathy and user experience design intuition",
      "Outstanding presentation and stakeholder management skills",
    ],
    requirements: [
      "Bachelor's degree in Engineering, Business, or related practical experience",
      "Proven track record of shipping customer-facing features",
      "Comfortable with agile methodologies in a remote setup",
    ],
  },
  {
    id: "full-stack-developer",
    title: "Full Stack Developer",
    team: "Technology",
    location: "Remote (India)",
    type: "Full-time",
    experience: "Mid-level (2–5 years)",
    postedText: "Posted 1 week ago",
    postedDays: 7,
    tags: ["React", "Node.js", "MongoDB", "TypeScript"],
    description:
      "Build and scale the GharPadharo platform to create meaningful impact. You will architect robust web applications, responsive user interfaces, and dependable backend APIs.",
    responsibilities: [
      "Develop clean, reusable components using React, Next.js, and modern CSS",
      "Design scalable RESTful and GraphQL APIs using Node.js and MongoDB",
      "Optimize application performance, accessibility, and cross-browser reliability",
      "Participate actively in code reviews, testing, and continuous integration",
      "Partner with product managers and designers to translate designs into code",
    ],
    skills: [
      "2–5 years of full stack web development experience",
      "Strong proficiency in JavaScript/TypeScript, React, and Node.js",
      "Hands-on experience with MongoDB or relational databases",
      "Familiarity with Tailwind CSS, state management, and modern build tools",
      "Solid understanding of web security, caching, and REST conventions",
    ],
    requirements: [
      "Degree in Computer Science, Software Engineering, or equivalent practical skills",
      "Experience writing testable, production-ready full stack code",
      "Strong problem-solving attitude and attention to code quality",
    ],
  },
  {
    id: "community-program-manager",
    title: "Community Program Manager",
    team: "Operations",
    location: "Remote",
    type: "Contract",
    experience: "Mid-level (2–5 years)",
    postedText: "Posted 1 week ago",
    postedDays: 7,
    tags: [
      "Community Building",
      "Partnerships",
      "Communication",
      "Program Management",
    ],
    description:
      "Lead community initiatives and partnerships to strengthen our ecosystem. You will drive outreach programs, organize events, and empower community members.",
    responsibilities: [
      "Plan and execute community engagement programs and digital meetups",
      "Cultivate strategic relationships with local community partners",
      "Gather community feedback, analyze sentiment, and share actionable insights",
      "Coordinate cross-functional campaigns with marketing and support teams",
      "Develop helpful resources, documentation, and member guidelines",
    ],
    skills: [
      "2–5 years in community management, partnerships, or operations",
      "Exceptional verbal and written communication in English and Hindi",
      "Strong program management and event moderation abilities",
      "High emotional intelligence, empathy, and active listening skills",
      "Experience managing community channels and digital tools",
    ],
    requirements: [
      "Track record of fostering active, supportive online/offline communities",
      "Ability to manage multiple concurrent initiatives with minimal supervision",
      "Available for contract engagement with prospective full-time transition",
    ],
  },
  {
    id: "content-creator",
    title: "Content Creator",
    team: "Marketing",
    location: "Remote",
    type: "Part-time",
    experience: "Fresher (0–1 years)",
    postedText: "Posted 2 weeks ago",
    postedDays: 14,
    tags: ["Content Writing", "Social Media", "Video Editing", "Storytelling"],
    description:
      "Create engaging content to showcase our stories, people, and impact. You'll produce creative multimedia assets that elevate GharPadharo's brand presence.",
    responsibilities: [
      "Produce compelling short-form videos, graphics, and social posts",
      "Write engaging articles, newsletters, and community spotlights",
      "Collaborate with the marketing team on content schedules and campaign themes",
      "Monitor engagement metrics and adapt creative formats to audience trends",
      "Maintain consistent brand voice and visual style across channels",
    ],
    skills: [
      "Creative storytelling and audience-first copywriting abilities",
      "Working knowledge of video editing tools and visual design apps",
      "Familiarity with social platforms (LinkedIn, Instagram, YouTube)",
      "Curious mindset with keen attention to aesthetics and tone",
      "Strong time management and collaborative spirit",
    ],
    requirements: [
      "Fresher or entry-level (0–1 years); portfolio or creative sample link required",
      "Passion for social impact and community empowerment",
      "Ability to commit to part-time schedule consistently",
    ],
  },
  {
    id: "data-scientist",
    title: "Data Scientist",
    team: "Data Science",
    location: "Remote",
    type: "Full-time",
    experience: "Mid-level (2–5 years)",
    postedText: "Posted 3 weeks ago",
    postedDays: 21,
    tags: ["Python", "SQL", "Data Visualization", "Machine Learning"],
    description:
      "Analyze data to drive strategic decisions and business growth. You will transform complex platform data into actionable predictive insights and models.",
    responsibilities: [
      "Extract, clean, and analyze complex datasets across platform databases",
      "Develop statistical models and machine learning pipelines for forecasting",
      "Build insightful dashboards and reports for leadership and operations",
      "Design and evaluate A/B experiments to measure platform features",
      "Translate ambiguous questions into rigorous analytical solutions",
    ],
    skills: [
      "2–5 years of hands-on data science and statistical analysis experience",
      "Advanced proficiency in Python (Pandas, NumPy, Scikit-Learn) and SQL",
      "Experience with data visualization tools and reporting dashboards",
      "Strong understanding of experimental design and statistical testing",
      "Effective communication skills to convey findings to non-technical teams",
    ],
    requirements: [
      "Degree in Data Science, Statistics, Mathematics, Computer Science, or related field",
      "Demonstrated experience handling real-world datasets and ETL pipelines",
      "Proactive analytical approach with attention to detail",
    ],
  },
];
