/**
 * Canonical Mock Applications Dataset
 * 
 * FRONTEND PROTOTYPE / DEMO DATA ONLY
 * - Not connected to any backend, database, or real candidates
 * - All names, contact details, resumes, and URLs are fictional demo placeholders
 * - References canonical jobs via `jobId` from @/lib/mockJobs
 * - Simplified two-state workflow: "new" (unread/pending review) or "viewed" (opened by admin)
 */
export const mockApplications = [
  {
    id: "application-001",
    jobId: "full-stack-developer",
    candidate: "Rahul Sharma",
    email: "rahul.sharma@example.com",
    phone: "+91 98765 43210",
    experience: "2 years",
    appliedAt: "2026-09-24T08:30:00Z",
    appliedText: "2 hours ago",
    status: "new",
    resume: "rahul-sharma-resume.pdf",
    coverLetter:
      "I'm interested in the Full Stack Developer role because I enjoy building products that solve practical problems. GharPadharo's focus on making property discovery simpler is especially interesting to me, and I'd like to contribute to the product from both the frontend and backend.",
    linkedin: "https://linkedin.com/in/rahul-sharma-demo",
    portfolio: "https://portfolio.example.com/rahul",
  },
  {
    id: "application-002",
    jobId: "content-creator",
    candidate: "Priya Rawat",
    email: "priya.rawat@example.com",
    phone: "+91 98765 43211",
    experience: "3 years",
    appliedAt: "2026-09-23T14:15:00Z",
    appliedText: "Yesterday",
    status: "new",
    resume: "priya-rawat-resume.pdf",
    coverLetter:
      "I love telling authentic stories about communities and living spaces. I would be thrilled to help GharPadharo share genuine stories of renters, PG residents, and local hosts across Uttarakhand.",
    linkedin: "https://linkedin.com/in/priya-rawat-demo",
    portfolio: "https://portfolio.example.com/priya",
  },
  {
    id: "application-003",
    jobId: "product-manager",
    candidate: "Arjun Mehta",
    email: "arjun.mehta@example.com",
    phone: "+91 98765 43212",
    experience: "4 years",
    appliedAt: "2026-09-22T11:00:00Z",
    appliedText: "2 days ago",
    status: "viewed",
    resume: "arjun-mehta-resume.pdf",
    coverLetter:
      "With 4 years leading consumer web applications, I focus heavily on reducing search friction for users. GharPadharo's mission to bridge property owners and room seekers aligns closely with how I like to design discovery roadmaps.",
    linkedin: "https://linkedin.com/in/arjun-mehta-demo",
    portfolio: "https://portfolio.example.com/arjun",
  },
  {
    id: "application-004",
    jobId: "data-scientist",
    candidate: "Neha Kapoor",
    email: "neha.kapoor@example.com",
    phone: "+91 98765 43213",
    experience: "3 years",
    appliedAt: "2026-09-20T16:45:00Z",
    appliedText: "4 days ago",
    status: "viewed",
    resume: "neha-kapoor-resume.pdf",
    coverLetter:
      "I specialize in clustering and predictive modeling for marketplace search dynamics. I'm excited by the opportunity at GharPadharo to extract actionable rental trends and price signals from listing data.",
    linkedin: "https://linkedin.com/in/neha-kapoor-demo",
    portfolio: "https://portfolio.example.com/neha",
  },
  {
    id: "application-005",
    jobId: "ai-research-scientist",
    candidate: "Aman Joshi",
    email: "aman.joshi@example.com",
    phone: "+91 98765 43214",
    experience: "3 years",
    appliedAt: "2026-09-17T09:20:00Z",
    appliedText: "7 days ago",
    status: "new",
    resume: "aman-joshi-resume.pdf",
    coverLetter:
      "My research centers on multimodal ranking and recommendation systems. Applying machine learning to match students and professionals with optimal PG and hostel listings at GharPadharo is an impactful challenge I'd love to tackle.",
    linkedin: "https://linkedin.com/in/aman-joshi-demo",
    portfolio: "https://portfolio.example.com/aman",
  },
  {
    id: "application-006",
    jobId: "full-stack-developer",
    candidate: "Kavya Singh",
    email: "kavya.singh@example.com",
    phone: "+91 98765 43215",
    experience: "3 years",
    appliedAt: "2026-09-14T15:00:00Z",
    appliedText: "10 days ago",
    status: "viewed",
    resume: "kavya-singh-resume.pdf",
    coverLetter:
      "I have built high-performance responsive web portals with Next.js, Node.js, and MongoDB. I appreciate GharPadharo's straightforward approach to rental discovery and look forward to scaling the core listing flows.",
    linkedin: "https://linkedin.com/in/kavya-singh-demo",
    portfolio: "https://portfolio.example.com/kavya",
  },
  {
    id: "application-007",
    jobId: "product-manager",
    candidate: "Rohan Verma",
    email: "rohan.verma@example.com",
    phone: "+91 98765 43216",
    experience: "2 years",
    appliedAt: "2026-09-10T12:10:00Z",
    appliedText: "14 days ago",
    status: "new",
    resume: "rohan-verma-resume.pdf",
    coverLetter:
      "I have managed candidate and consumer booking portals, prioritizing clean workflows and user research. GharPadharo's focus on transparent room discovery is a fantastic product area to grow.",
    linkedin: "https://linkedin.com/in/rohan-verma-demo",
    portfolio: "https://portfolio.example.com/rohan",
  },
  {
    id: "application-008",
    jobId: "community-program-manager",
    candidate: "Ananya Gupta",
    email: "ananya.gupta@example.com",
    phone: "+91 98765 43217",
    experience: "4 years",
    appliedAt: "2026-09-06T10:00:00Z",
    appliedText: "18 days ago",
    status: "new",
    resume: "ananya-gupta-resume.pdf",
    coverLetter:
      "Building trustworthy networks of property owners, hostel caretakers, and tenants requires empathy and hands-on community engagement. I have led regional community initiatives and would love to spearhead this for GharPadharo.",
    linkedin: "https://linkedin.com/in/ananya-gupta-demo",
    portfolio: "https://portfolio.example.com/ananya",
  },
  {
    id: "application-009",
    jobId: "data-scientist",
    candidate: "Vivek Negi",
    email: "vivek.negi@example.com",
    phone: "+91 98765 43218",
    experience: "1 year",
    appliedAt: "2026-09-04T17:30:00Z",
    appliedText: "20 days ago",
    status: "viewed",
    resume: "vivek-negi-resume.pdf",
    coverLetter:
      "As a junior data analyst with strong Python and SQL skills, I am eager to contribute to rental analytics and market data ingestion pipelines at GharPadharo.",
    linkedin: "https://linkedin.com/in/vivek-negi-demo",
    portfolio: "https://portfolio.example.com/vivek",
  },
  {
    id: "application-010",
    jobId: "content-creator",
    candidate: "Simran Khanna",
    email: "simran.khanna@example.com",
    phone: "+91 98765 43219",
    experience: "4 years",
    appliedAt: "2026-09-03T09:00:00Z",
    appliedText: "21 days ago",
    status: "new",
    resume: "simran-khanna-resume.pdf",
    coverLetter:
      "I produce short-form video tours and lifestyle guides showcasing local neighborhoods and living quarters. Helping newcomers find comfort through GharPadharo's content channels is an inspiring mission.",
    linkedin: "https://linkedin.com/in/simran-khanna-demo",
    portfolio: "https://portfolio.example.com/simran",
  },
];
